# Generated by Django 5.1 on 2024-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_tag_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
