# Generated by Django 5.1 on 2024-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('salad', 'Salad'), ('snack', 'Snack'), ('soup', 'Soup'), ('drink', 'Drink'), ('breakfast', 'Breakfast'), ('side_dish', 'Side Dish')], default='main_course', max_length=20),
        ),
    ]
