# Generated by Django 5.1 on 2024-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
