# Generated by Django 5.1 on 2024-09-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0002_rename_name_shoppinglist_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='shopping_lists.shoppinglist'),
        ),
    ]
