# Generated by Django 5.1 on 2024-09-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0003_alter_ingredientitem_shopping_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='item',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
